version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception_network

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    networks:
      - inception_network
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    restart: always
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - inception_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/zoukaddo/data/wordpress_data
      o: bind
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: /Users/zoukaddo/data/mariadb_data
      o: bind

networks:
  inception_network:
    driver: bridge