#!/bin/bash

service mysql start

mysql> CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE ;
mysql> CREATE USER IF NOT EXISTS $MYSQL_USER@% IDENTIFIED BY $MYSQL_PASSWORD ;
mysql> GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO $MYSQL_USER@% ;
mysql> FLUSH PRIVILEGES;

mysqld